title: maplesteve.com
description:
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

include: ["_pages"]
exclude: [vendor]

collections:
  tags:
    output: true
    permalink: /tag/:name/

defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: blog_by_tag
